#!/usr/bin/env python
# coding: utf-8
"""
Script process the GW output generated by GWsetup using VASP or ABINIT.
"""
from __future__ import unicode_literals, division, print_function, absolute_import
import os.path
import sys
from HTGW.flows.datastructures import get_spec

__author__ = "Michiel van Setten"
__copyright__ = " "
__version__ = "0.9"
__maintainer__ = "Michiel van Setten"
__email__ = "mjvansetten@gmail.com"
__date__ = "May 2014"


MODULE_DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    """
    main gw output processing
    """
    if os.path.isfile('plots'):
        os.remove('plots')
    if os.path.isfile('plot-fits'):
        os.remove('plot-fits')
    spec = get_spec('GW')
    spec.read_from_file('spec.in')
    print('Found setup for ', spec.get_code())
    counters = spec.loop_structures('o')
    return counters

if __name__ == "__main__":
    sys.exit(main())
